version: "3.1"
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      load_data:
        condition: service_completed_successfully

  load_data:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo
    command: python load_data.py

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: hard_password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: hard_password
      ME_CONFIG_MONGODB_URL: mongodb://username:hard_password@mongo:27017/
